# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_room(object):
    def setupUi(self, room):
        room.setObjectName("room")
        room.resize(116, 24)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(room)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.holder = QtWidgets.QVBoxLayout()
        self.holder.setObjectName("holder")
        self.verticalLayout_2.addLayout(self.holder)

        self.retranslateUi(room)
        QtCore.QMetaObject.connectSlotsByName(room)

    def retranslateUi(self, room):
        _translate = QtCore.QCoreApplication.translate
        room.setWindowTitle(_translate("room", "Form"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    room = QtWidgets.QWidget()
    ui = Ui_room()
    ui.setupUi(room)
    room.show()
    sys.exit(app.exec_())
