# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rooms.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from room import Ui_room

rooms = {
    'room1': ['ori', 'ilay', 'yossi'],
    'room2': ['ori', 'ilay', 'yossi'],
    'room3': ['ori', 'ilay', 'yossi']
}


class Ui_MainWindow(object):
    def __init__(self):
        self.status_bar = QtWidgets.QStatusBar(MainWindow)
        self.central_widget = QtWidgets.QWidget(MainWindow)
        self.formLayoutWidget = QtWidgets.QWidget(self.central_widget)
        self.menu_bar = QtWidgets.QMenuBar(MainWindow)
        self.menu_info = QtWidgets.QMenu(self.menu_bar)
        self.menu_settings = QtWidgets.QMenu(self.menu_bar)
        self.room_info = QtWidgets.QPushButton(self.formLayoutWidget)
        self.my_ip_label = QtWidgets.QLabel(self.formLayoutWidget)
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(520, 417)
        self.central_widget.setObjectName("centralwidget")
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 521, 421))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        font = QtGui.QFont()
        font.setPointSize(20)
        self.my_ip_label.setFont(font)
        self.my_ip_label.setMouseTracking(False)
        self.my_ip_label.setAutoFillBackground(True)
        self.my_ip_label.setAlignment(QtCore.Qt.AlignCenter)
        self.my_ip_label.setObjectName("my_ip_label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.my_ip_label)

        for room_name, members in rooms.items():
            room = Ui_room()
            _room = {Ui_room.setObjectName(room, room_name), Ui_room.setFixedWidth(room, 350), Ui_room.setWindowTitle(room, "a0")}
            Ui_room.setupUi(room, _room=_room, members=members, _room_name=room_name)

        self.room_info.setObjectName("room_info")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.room_info)

        MainWindow.setCentralWidget(self.central_widget)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 520, 26))
        self.menu_bar.setObjectName("menubar")
        self.menu_settings.setObjectName("menusettings")
        self.menu_info.setObjectName("menuinfo")
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.status_bar)
        self.menu_bar.addAction(self.menu_settings.menuAction())
        self.menu_bar.addAction(self.menu_info.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.my_ip_label.setText(_translate("MainWindow", "your ip is: {ip}"))
        self.menu_settings.setTitle(_translate("MainWindow", "settings"))
        self.menu_info.setTitle( _translate( "MainWindow", "info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())


